# Generated by Django 3.2.9 on 2021-12-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('email3', models.EmailField(max_length=254)),
                ('cellphone', models.TextField(max_length=11)),
                ('phone', models.TextField(max_length=11)),
                ('cnpj', models.TextField(max_length=18)),
            ],
        ),
    ]
