# Generated by Django 3.2.9 on 2021-12-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_scratch', models.BooleanField()),
                ('tires_good', models.BooleanField()),
                ('kilometers', models.DecimalField(decimal_places=1, max_digits=10)),
                ('lights_working', models.BooleanField()),
                ('panel_lights', models.BooleanField()),
                ('brake_lights', models.BooleanField()),
                ('seats', models.BooleanField()),
                ('roof', models.BooleanField()),
                ('is_clean', models.BooleanField()),
                ('glasses', models.BooleanField()),
                ('observations', models.TextField()),
                ('gps_working', models.BooleanField()),
                ('lock_working', models.BooleanField()),
                ('fuel_liters', models.DecimalField(decimal_places=3, max_digits=100)),
                ('security_items', models.BooleanField()),
                ('oil', models.BooleanField()),
                ('water', models.BooleanField()),
                ('brake_fluid', models.BooleanField()),
                ('singed_customer', models.BooleanField()),
                ('singed_employee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
