# Generated by Django 3.2.9 on 2021-12-10 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.TextField(max_length=7)),
                ('color', models.TextField()),
                ('brand', models.TextField()),
                ('car_model', models.TextField()),
                ('chassi_number', models.TextField()),
                ('renavam', models.TextField()),
                ('have_gps', models.BooleanField()),
                ('is_for_pcd', models.BooleanField()),
                ('kilometers', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fuel_liters', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField()),
                ('return_date', models.DateField()),
                ('is_approved', models.BooleanField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_returned', models.BooleanField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='core.vehicle')),
            ],
        ),
    ]
