# Generated by Django 3.2.9 on 2021-12-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='chassi_number',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.TextField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='renavam',
            field=models.TextField(unique=True),
        ),
    ]
